name: API Documentation

on:
  push:
    branches:
      - doc

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install torch torchvision torchaudio
          python -m pip install --no-build-isolation 'git+https://github.com/facebookresearch/detectron2.git'
          # Install Sphinx and the Read the Docs theme
          pip install sphinx sphinx_rtd_theme

      # Adjust these paths according to where your conf.py and index.rst are located.
      # If conf.py and index.rst are inside docs/:
      - name: Generate RST files from code
        run: sphinx-apidoc -o docs/source/ vit_flexible_heads/

      - name: Build documentation
        run: sphinx-build -b html docs/source docs/build/html

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
